<?php

namespace AppBundle\Repository;

/**
 * groupsLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsLogsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findGroupLog($userId, $groupId)
    {
        return $this->createQueryBuilder('q')
            ->select('q')
            ->where('q.userId = :userId AND q.groupId = :groupId')
            ->setParameter('userId', $userId)
            ->setParameter('groupId', $groupId)
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function findUsersIdsByGroupId($groupId)
    {
        return $this->createQueryBuilder('q')
            ->select('q.userId')
            ->where('q.groupId = :groupId')
            ->setParameter('groupId', $groupId)
            ->getQuery()
            ->getArrayResult();
    }
}
