# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    manage_service:
        class: AppBundle\Service\ManageService
        arguments:
            - '@doctrine.orm.default_entity_manager'
